services:
  docs:
    image: duck_tracker_local_docs
    container_name: duck_tracker_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./duck_tracker:/app/duck_tracker:z
    ports:
      - '9000:9000'
    command: /start-docs
